version: '3.8'

services:
  app:
    image: streamfort-app
    ports:
      - "8552:8552"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=seguranca
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'seguranca'
    ports:
      - "20307:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mysql_data:/var/lib/mysql
      - ./reference/database/implantation_seguranca.sql:/docker-entrypoint-initdb.d/implantation_seguranca.sql

volumes:
  mysql_data:
