services:
  app:
    image: streamfort-app
    ports:
      - "8552:8552"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=20307
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=seguranca
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql-ptbr2
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'seguranca'
    ports:
      - "20307:20307"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./reference/database/implantation_seguranca.sql:/docker-entrypoint-initdb.d/implantation_seguranca.sql

volumes:
  mysql_data:
